[server]
baseUrlPath = "app"
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor="#FAFAFA"
backgroundColor="#0E1117"
secondaryBackgroundColor="#1A1C24"
textColor="#FAFAFA"

# Set custom Google Fonts directly
font="sans serif"